services:
  postgres-cache:
    image: postgres:17
    container_name: postgres-cache
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    ports:
      - "5438:5432"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/01-setup.sql
      - postgres-data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c shared_buffers_type=slab
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s

volumes:
  postgres-data:
