services:
  # Primary (write)
  postgres-primary:
    image: postgres:17
    container_name: pg-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_pass
    ports:
      - "5435:5432"
    volumes:
      - primary-data:/var/lib/postgresql/data
      - ./setup-primary.sql:/docker-entrypoint-initdb.d/01-setup.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: >
      postgres
      -c max_wal_senders=10
      -c wal_level=replica
      -c hot_standby=on
      -c wal_keep_size=1GB
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s

  # Replica 1 (read)
  postgres-replica-1:
    image: postgres:17
    container_name: pg-replica-1
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      PGSTANDBY: 1
    ports:
      - "5436:5432"
    volumes:
      - replica1-data:/var/lib/postgresql/data
    depends_on:
      postgres-primary:
        condition: service_healthy
    command: >
      bash -ec "until pg_isready -h postgres-primary -U postgres; do sleep 1; done;
      rm -rf /var/lib/postgresql/data/*;
      export PGPASSWORD=replicator_pass;
      pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U replicator -P -w -R -X fetch;
      chmod 700 /var/lib/postgresql/data;
      exec postgres"

  # Replica 2 (read)
  postgres-replica-2:
    image: postgres:17
    container_name: pg-replica-2
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      PGSTANDBY: 1
    ports:
      - "5437:5432"
    volumes:
      - replica2-data:/var/lib/postgresql/data
    depends_on:
      postgres-primary:
        condition: service_healthy
    command: >
      bash -ec "until pg_isready -h postgres-primary -U postgres; do sleep 1; done;
      rm -rf /var/lib/postgresql/data/*;
      export PGPASSWORD=replicator_pass;
      pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U replicator -P -w -R -X fetch;
      chmod 700 /var/lib/postgresql/data;
      exec postgres"

volumes:
  primary-data:
  replica1-data:
  replica2-data:
